version: "3.0"
services:
    # Frontend(Vue + Nuxt)
    frontend:
        build:
            context: ./Frontend
        tty: true
        ports:
            - "80:80"
        volumes:
            - ./Frontend/Src:/app

    # Backend(Golang)
    backend:
        build:
            context: ./Backend
        tty: true
        ports:
            - "3000:3000"
        volumes:
            - ./Backend:/go/src/authapp
        depends_on:
            - db

    # Database(MySQL)
    db:
        image: mysql:5.7
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --innodb-use-native-aio=0
        ports:
            - "3306:3306"
        volumes:
            - ./Ignore/MySQL/data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: develop
            MYSQL_PASSWORD: develop
            TZ: Asia/Tokyo
            